spring.application.name=relay

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/relay_db

# Server Configuration
server.port=8080

# Ethereum / Web3j configuration (Ganache)
blockchain.rpc.url=http://127.0.0.1:7545
ethereum.rpc.url=http://127.0.0.1:7545
blockchain.private.key=0xe9719fbbfbaae48e26166bab9d99242afb61ff1ff87c8203b66ce3ec702b27aa
blockchain.nodeRegistry.address=0xF50eD905643a1c284BC16060456A89CE67a0fCE6
blockchain.reputationLedger.address=0x6e7B89f89cE24eE6F3498B97EC157197112A4A12
