spring.application.name=relay

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/relay_db

# Server Configuration
server.port=8080

# Ethereum / Web3j configuration (Ganache)
blockchain.rpc.url=http://127.0.0.1:7545
ethereum.rpc.url=http://127.0.0.1:7545
blockchain.private.key=0xe9719fbbfbaae48e26166bab9d99242afb61ff1ff87c8203b66ce3ec702b27aa
blockchain.nodeRegistry.address=0x9ecEA68DE55F316B702f27eE389D10C2EE0dde84
blockchain.reputationLedger.address=0x70421b24F60dBA871e30442Ad43EFd44ff9E3A81
